version: '3.8'

services:
  app:
    build: .
    container_name: foodordering-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/foodorderingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: foodordering-db
    restart: always
    environment:
      POSTGRES_DB: foodorderingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # External port 5433 â†’ Container port 5432 [bind container's internal port(Postgres inside Docker ) to local port 5433]
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
